import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Blurry rectangle - positioned independently */}
        <div className="fixed left-1/2 -translate-x-1/2 top-0 z-5 w-full h-15 backdrop-blur-md bg-white/10 pointer-events-none select-none" />
        
        {/* Logo - positioned independently */}
        <div className="fixed left-1/2 -translate-x-1/2 top-2.5 z-10 flex items-center justify-center pointer-events-none select-none">
          <Image
            src="/dt logo.png"
            alt="Doctor Towels Logo"
            width={100}
            height={100}
            className="object-contain drop-shadow-lg"
            priority
          />
        </div>
        
        <div className="relative w-screen h-screen overflow-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
